###
GET http://localhost:3000/todos/?status=TO%20DO

###
GET http://localhost:3000/todos/?priority=HIGH

###
GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS

###
GET http://localhost:3000/todos/?search_q=Buy

###
GET http://localhost:3000/todos/?category=WORK&status=DONE

###
GET http://localhost:3000/todos/?category=HOME

###
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

###
GET http://localhost:3000/todos/1/

###
GET http://localhost:3000/todos/2/

###
GET http://localhost:3000/todos/3/

###
GET http://localhost:3000/todos/4/

###
GET http://localhost:3000/todos/5/

###
GET http://localhost:3000/agenda/

###
GET http://localhost:3000/agenda/?date=2021-04-04

###
GET http://localhost:3000/agenda/?date=2020-09-22

###
GET http://localhost:3000/agenda/?date=2021-02-22

###
GET http://localhost:3000/agenda/?date=2021-01-12

###
GET http://localhost:3000/agenda/?date=2021-04-02

###
GET http://localhost:3000/agenda/?date=2021-13-15